version: '3.9'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 127.0.0.1:8000:8000
    env_file:
      - .env